spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://core-factu-api-pgsql:5432/cookies_store}
    username: ${SPRING_DATASOURCE_USERNAME:core}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_REDIS_HOST:core-factu-api-redis}
      port: ${SPRING_REDIS_PORT:6379}
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

admin:
  bootstrap:
    super-admin:
      enabled: ${STAGING_SUPER_ADMIN_ENABLED:true}
      email: ${STAGING_SUPER_ADMIN_EMAIL:staging.admin@cookiesstore.local}
      password: ${STAGING_SUPER_ADMIN_PASSWORD:admin123}
      domains: ${STAGING_SUPER_ADMIN_DOMAINS:main-store,example.test}
